on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: findissuekey
        with:
          string: ${{ github.event.pull_request.title }}

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.findissuekey.outputs.issue }}
          transition: "Done"
