on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: atlassian/gajira-login@master
        continue-on-error: true
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find Issue Key
        uses: atlassian/gajira-find-issue-key@master
        continue-on-error: true
        id: findissuekey
        with:
          string: ${{ github.event.pull_request.title }}

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        continue-on-error: true
        with:
          issue: ${{ steps.findissuekey.outputs.issue }}
          transition: "Done"
