on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 315199611892.dkr.ecr.eu-west-2.amazonaws.com
          ECR_REPOSITORY: ecr-repo-name
          IMAGE_TAG: asdfghjklzxcvbnmqwertyuiop
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Log out of Amazon ECR
        if: always()
        run: docker logout 315199611892.dkr.ecr.eu-west-2.amazonaws.com
      - name: Clean up old Docker images
        run: docker system prune -a -f
      - name: Slack Notification
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: coincover-devops-alert
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://assets.coincover.com/images/logo-square.png
          SLACK_TITLE: 'Message :partyparrot: '
          SLACK_MESSAGE: '@here Successful, all checks passed :white_check_mark: Review using the link'
          SLACK_USERNAME: Github
          MSG_MINIMAL: event,commit,ref
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACKWEBHOOK }}
          SLACK_MSG_AUTHOR: ${{ github.actor }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_CHANNEL: coincover-devops-alert
          SLACK_COLOR: '#CC0000'
          SLACK_ICON: https://assets.coincover.com/images/logo-square.png
          SLACK_TITLE: 'Message :fire::fire::fire:'
          SLACK_MESSAGE: '@here Something failed :x:  Review using the link'
          SLACK_USERNAME: Github
          MSG_MINIMAL: event,commit,ref
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACKWEBHOOK }}
          SLACK_MSG_AUTHOR: ${{ github.actor }}
