on:
  pull_request:
    branches:
      - main
jobs:
  test-unit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          export GOPATH=$HOME/go && \
          export GOBIN=$GOPATH/bin && \
          export PATH=$GOBIN:$PATH:/usr/local/go/bin && \
          make clean test-unit
      - name: Checkout
        uses: actions/checkout@master
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find issue key in commit
        it: find_key
        uses: HighwayThree/jira-extract-issue-keys@master
        with:
            is-pull-request: ${{ github.event_name == 'pull_request' }}
            parse-all-commits: ${{ github.event_name == 'push' }}
            commit-message: ''
      - name: Transition Issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.find_key.outputs.issue }}
          transition: "In Progress"
