on:
  pull_request:
    branches:
      - main
jobs:
  test-unit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          export GOPATH=$HOME/go && \
          export GOBIN=$GOPATH/bin && \
          export PATH=$GOBIN:$PATH:/usr/local/go/bin && \
          make clean test-unit
      - name: Checkout
        uses: actions/checkout@master

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find in commit messages
        id: find
        run : |
          ISSUE_KEY=$(git log --format=%B -n 1 ${{ github.event.after }}) >> $GITHUB_ENV

      - name: Transition issue
        uses: tuanddd/jira-automate-transition@v1.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-to-move-to-when-review-requested: To Do
          column-to-move-to-when-changes-requested: In Progress
          column-to-move-to-when-merged: Done
          jira-issue-id: ${{env.ISSUE_KEY}}
