on:
  pull_request:
    branches:
      - main
jobs:
  test-unit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          export GOPATH=$HOME/go && \
          export GOBIN=$GOPATH/bin && \
          export PATH=$GOBIN:$PATH:/usr/local/go/bin && \
          make clean test-unit
      - name: Extract PR Number
        shell: bash
        run: echo "##[set-output name=pr;]$(echo $GITHUB_REF | sed -E 's/^refs\/pull\/(.*)\/merge$/\1/')"
        id: extract_pr_number
      - name: Slack Notification
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: coincover-devops-alert
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://assets.coincover.com/images/logo-square.png
          SLACK_TITLE: 'Message :partyparrot: '
          SLACK_MESSAGE: '@here All checks have passed :white_check_mark: Review pull request using the link https://github.com/${{ github.actor }}/app/pull/${{ steps.extract_pr_number.outputs.pr }}'
          SLACK_USERNAME: Github
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACKWEBHOOK }}
          SLACK_MSG_AUTHOR: ${{ github.actor }}
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: coincover-devops-alert
          SLACK_COLOR: '#CC0000'
          SLACK_ICON: https://assets.coincover.com/images/logo-square.png
          SLACK_TITLE: 'Message :fire::fire::fire:'
          SLACK_MESSAGE: '@here Something failed :x: Review pull request using the link https://github.com/${{ github.actor }}/app/pull/${{ steps.extract_pr_number.outputs.pr }}'
          SLACK_USERNAME: Github
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACKWEBHOOK }}
          SLACK_MSG_AUTHOR: ${{ github.actor }}
