on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 315199611892.dkr.ecr.eu-west-2.amazonaws.com
          ECR_REPOSITORY: ecr-repo-name
          IMAGE_TAG: asdfghjklzxcvbnmqwertyuiop
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  job2:
    runs-on: self-hosted
    steps:
      - name: Log out of Amazon ECR
        if: always()
        run: docker logout 315199611892.dkr.ecr.eu-west-2.amazonaws.com
  job3:
    runs-on: self-hosted
    steps:
      - name: Clean up old Docker images
        run: docker system prune -a -f
  job4:
    runs-on: self-hosted
    steps:
      - name: test Fail
        run: |
          exit 1

  job10:
    runs-on: self-hosted
    needs: [job1, job2, job3, job4]
    if: (needs.job1.result == 'success' || needs.job2.result == 'success'|| needs.job3.result == 'success' || needs.job4.result == 'success')
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
          SLACK_CHANNEL: coincover-devops-alert
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://assets.coincover.com/images/logo-square.png
          SLACK_TITLE: 'Message :partyparrot:  successful: @here'
          SLACK_MESSAGE: ''
          SLACK_USERNAME: Github
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACKWEBHOOK }}
          SLACK_MSG_AUTHOR: ${{ github.actor }}
      - name: Slack Notification Post
        run: |
          echo "$NEEDS_CONTEXT"
  run-if-failed:
    runs-on: self-hosted
    needs: [job1, job2, job3, job4]
    if: always() && (needs.job1.result == 'failure' || needs.job2.result == 'failure'|| needs.job3.result == 'failure' || needs.job4.result == 'failure')
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
          SLACK_CHANNEL: coincover-devops-alert
          SLACK_COLOR: '#CC0000'
          SLACK_ICON: https://assets.coincover.com/images/logo-square.png
          SLACK_TITLE: 'Message :fire::fire::fire:  something failed:'
          SLACK_MESSAGE: '@here'
          SLACK_MESSAGE: ''
          SLACK_USERNAME: Github
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACKWEBHOOK }}
          SLACK_MSG_AUTHOR: ${{ github.actor }}
      - name: Slack Notification Post
        run: |
          echo "$NEEDS_CONTEXT"
