on:
  pull_request:
    branches:
      - main
jobs:
  test-unit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          export GOPATH=$HOME/go && \
          export GOBIN=$GOPATH/bin && \
          export PATH=$GOBIN:$PATH:/usr/local/go/bin && \
          make clean test-unit
      - name: Checkout
        uses: actions/checkout@master
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        id: find    
        with:
          pattern: '\[[^]]+\] .+$'
          error: 'Your first line has to contain a commit type like "[BUGFIX]".'
      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.find.outputs.issue }}
          transition: "In progress"
