on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Slack Notification
        uses: actions/checkout@v2
        env:
          SLACK_CHANNEL: coincover-devops-alert
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Post Content :partyparrot:'
          SLACK_TITLE: 'Message: '
          SLACK_USERNAME: patricia
          SLACK_WEBHOOK: ${{ secrets.SLACKWEBHOOK }}
          SLACK_MSG_AUTHOR: $GITHUB_ACTOR
