on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: coincover-devops-alert
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://assets.coincover.com/images/logo-square.png
          SLACK_TITLE: 'Message: '
          SLACK_MESSAGE: ':partyparrot: @${{ github.actor }} pushed commits!'
          SLACK_USERNAME: patricia
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACKWEBHOOK }}
          SLACK_MSG_AUTHOR: ${{ github.actor }}
          SLACK_ICON_EMOJI: :partyparrot:
